### ISSUE TITLE
Сбитая кодировка

### ISSUE THREAD

**Issue by pozitronik** [automatize-it/Chrome_extension_Habr_comments_control#1]
![image](https://user-images.githubusercontent.com/2357892/51174517-043b5080-18c9-11e9-9ac5-e9d934a62692.png)

Firefox Nightly 66.0a1

**Comment by pozitronik** [comment]
Помогло переключение опции **Text Encoding for Legacy Content** с Default на Cyrrilic, но, думаю, расширение само должно сообщать корректную локаль.

**Comment by automatize-it** [comment]
Исправлено, задана UTF в явном виде
