### ISSUE TITLE
Скрывается открытый по ссылке комментарий, если включена настройка "развернуть по умолчанию"

### ISSUE THREAD

**Issue by EviGL** [automatize-it/Chrome_extension_Habr_comments_control#5]
Версия 0.5, Firefox.
Видимо, при включении настройки "развернуть по умолчанию" код, обрабатывающий случай открытия комментария по ссылке, отрабатывает некорректно и наоборот сворачивает ветку с искомым комментарием.

Вот пример, хотя сработает любая ссылка: https://habr.com/ru/post/445136/#comment_19974600

**Comment by automatize-it** [comment]
Спасибо, что обратили внимание.
Буду проверять и исправлять.

**Comment by automatize-it** [comment]
Исправлено
