### ISSUE TITLE
Рейтинги комментариев не видны независимо от настройки

### ISSUE THREAD

**Issue by RuslanGetmansky** [automatize-it/Chrome_extension_Habr_comments_control#7]
![invisible_rates](https://user-images.githubusercontent.com/1990783/71808248-f81a4700-3075-11ea-89c6-9c03f328e447.png)

**Comment by automatize-it** [comment]
Подтверждаю. Буду разбираться

**Comment by automatize-it** [comment]
Проблема связана с лишним кодом в блоке обработки длинных комментариев для их последующего сворачивания.
Оценки скрываются при использовании опции "полускрыть длинные".

**Comment by automatize-it** [comment]
Исправлено.
